# Generated by Django 3.0.8 on 2020-07-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('street_address', models.CharField(max_length=30)),
                ('apt_address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('zip_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=30)),
                ('place_for_guests', models.IntegerField()),
                ('place_location', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAndGuestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('guests_to_accommodate', models.IntegerField()),
                ('bedrooms_guests_can_use', models.IntegerField()),
                ('beds_guests_can_use', models.IntegerField()),
                ('total_bedroom_beds', models.IntegerField()),
                ('total_common_space_beds', models.IntegerField()),
            ],
        ),
    ]
